export const interiorFeaturesOptions = [
  { label: 'Living room', value: 'livingroom' },
  { label: 'Dining room', value: 'diningroom' },
  { label: 'Kitchen', value: 'kitchen' },
  { label: 'Open-plan kitchen', value: 'openkitchen' },
  { label: 'Fully furnished', value: 'fullyfurnished' },
  { label: 'Partially furnished', value: 'partiallyfurnished' },
  { label: 'Unfurnished', value: 'unfurnished' },
  { label: 'Built-in wardrobes', value: 'builtinwardrobes' },
  { label: 'Air conditioning', value: 'airconditioning' },
  { label: 'Heating', value: 'heating' },
  { label: 'Fireplace', value: 'fireplace' },
  { label: 'Balcony', value: 'balcony' },
  { label: 'Terrace', value: 'terrace' },
  { label: 'Laundry room', value: 'laundryroom' },
  { label: 'Storage room', value: 'storageroom' },
  { label: 'Smart home system', value: 'smarthomesystem' }
]

export const buildingFeaturesOptions = [
  { label: 'Elevator', value: 'elevator' },
  { label: 'Doorman service', value: 'doormanservice' },
  { label: 'Security system', value: 'securitysystem' },
  { label: '24h surveillance', value: 'surveillance24h' },
  { label: 'Concierge service', value: 'conciergeservice' },
  { label: 'Gated community', value: 'gatedcommunity' },
  { label: 'Wheelchair accessible', value: 'wheelchairaccessible' }
]

export const outdoorFeaturesOptions = [
  { label: 'Private pool', value: 'privateswimmingpool' },
  { label: 'Communal pool', value: 'communalswimmingpool' },
  { label: 'Private garden', value: 'privategarden' },
  { label: 'Communal garden', value: 'communalgarden' },
  { label: 'Playground', value: 'playground' },
  { label: 'Gym', value: 'gym' },
  { label: 'Rooftop', value: 'rooftop' },
  { label: 'Solarium', value: 'solarium' },
  { label: 'Barbecue area', value: 'barbecuearea' },
  { label: 'Sports facilities', value: 'sportsfacilities' },
  { label: 'Clubhouse', value: 'clubhouse' },
  { label: 'Community room', value: 'communityroom' }
]

export const parkingTransportOptions = [
  { label: 'Private parking', value: 'privateparking' },
  { label: 'Communal parking', value: 'communalparking' },
  { label: 'Underground garage', value: 'undergroundgarage' },
  { label: 'Bicycle storage', value: 'bicyclestorage' },
  { label: 'EV charging point', value: 'evchargingpoint' },
  { label: 'Near station or stop', value: 'nearstation' },
  { label: 'Good public transport connection', value: 'goodpublictransport' }
]

export const provincesOfSpain = [
  { label: 'Álava', value: 'alava' },
  { label: 'Albacete', value: 'albacete' },
  { label: 'Alicante', value: 'alicante' },
  { label: 'Almería', value: 'almeria' },
  { label: 'Asturias', value: 'asturias' },
  { label: 'Ávila', value: 'avila' },
  { label: 'Badajoz', value: 'badajoz' },
  { label: 'Barcelona', value: 'barcelona' },
  { label: 'Burgos', value: 'burgos' },
  { label: 'Cáceres', value: 'caceres' },
  { label: 'Cádiz', value: 'cadiz' },
  { label: 'Cantabria', value: 'cantabria' },
  { label: 'Castellón', value: 'castellon' },
  { label: 'Ciudad Real', value: 'ciudad real' },
  { label: 'Córdoba', value: 'cordoba' },
  { label: 'Cuenca', value: 'cuenca' },
  { label: 'Girona', value: 'girona' },
  { label: 'Granada', value: 'granada' },
  { label: 'Guadalajara', value: 'guadalajara' },
  { label: 'Guipúzcoa', value: 'guipuzcoa' },
  { label: 'Huelva', value: 'huelva' },
  { label: 'Huesca', value: 'huesca' },
  { label: 'Illes Balears', value: 'illes balears' },
  { label: 'Jaén', value: 'jaen' },
  { label: 'A Coruña', value: 'a coruna' },
  { label: 'La Rioja', value: 'la rioja' },
  { label: 'Las Palmas', value: 'las palmas' },
  { label: 'León', value: 'leon' },
  { label: 'Lleida', value: 'lleida' },
  { label: 'Lugo', value: 'lugo' },
  { label: 'Madrid', value: 'madrid' },
  { label: 'Málaga', value: 'malaga' },
  { label: 'Murcia', value: 'murcia' },
  { label: 'Navarra', value: 'navarra' },
  { label: 'Ourense', value: 'ourense' },
  { label: 'Palencia', value: 'palencia' },
  { label: 'Pontevedra', value: 'pontevedra' },
  { label: 'Salamanca', value: 'salamanca' },
  { label: 'Santa Cruz de Tenerife', value: 'santa cruz de tenerife' },
  { label: 'Segovia', value: 'segovia' },
  { label: 'Sevilla', value: 'sevilla' },
  { label: 'Soria', value: 'soria' },
  { label: 'Tarragona', value: 'tarragona' },
  { label: 'Teruel', value: 'teruel' },
  { label: 'Toledo', value: 'toledo' },
  { label: 'Valencia', value: 'valencia' },
  { label: 'Valladolid', value: 'valladolid' },
  { label: 'Vizcaya', value: 'vizcaya' },
  { label: 'Zamora', value: 'zamora' },
  { label: 'Zaragoza', value: 'zaragoza' }
]

export const departmentsOfFrance = [
  { label: 'Ain', value: 'ain' },
  { label: 'Aisne', value: 'aisne' },
  { label: 'Allier', value: 'allier' },
  { label: 'Alpes-de-Haute-Provence', value: 'alpes-de-haute-provence' },
  { label: 'Hautes-Alpes', value: 'hautes-alpes' },
  { label: 'Alpes-Maritimes', value: 'alpes-maritimes' },
  { label: 'Ardèche', value: 'ardeche' },
  { label: 'Ardennes', value: 'ardennes' },
  { label: 'Ariège', value: 'ariege' },
  { label: 'Aube', value: 'aube' },
  { label: 'Aude', value: 'aude' },
  { label: 'Aveyron', value: 'aveyron' },
  { label: 'Bouches-du-Rhône', value: 'bouches-du-rhone' },
  { label: 'Calvados', value: 'calvados' },
  { label: 'Cantal', value: 'cantal' },
  { label: 'Charente', value: 'charente' },
  { label: 'Charente-Maritime', value: 'charente-maritime' },
  { label: 'Cher', value: 'cher' },
  { label: 'Corrèze', value: 'correze' },
  { label: 'Corse-du-Sud', value: 'corse-du-sud' },
  { label: 'Haute-Corse', value: 'haute-corse' },
  { label: "Côte-d'Or", value: 'cote-dor' },
  { label: "Côtes-d'Armor", value: 'cotes-darmor' },
  { label: 'Creuse', value: 'creuse' },
  { label: 'Dordogne', value: 'dordogne' },
  { label: 'Doubs', value: 'doubs' },
  { label: 'Drôme', value: 'drome' },
  { label: 'Eure', value: 'eure' },
  { label: 'Eure-et-Loir', value: 'eure-et-loir' },
  { label: 'Finistère', value: 'finistere' },
  { label: 'Gard', value: 'gard' },
  { label: 'Haute-Garonne', value: 'haute-garonne' },
  { label: 'Gers', value: 'gers' },
  { label: 'Gironde', value: 'gironde' },
  { label: 'Hérault', value: 'herault' },
  { label: 'Ille-et-Vilaine', value: 'ille-et-vilaine' },
  { label: 'Indre', value: 'indre' },
  { label: 'Indre-et-Loire', value: 'indre-et-loire' },
  { label: 'Isère', value: 'isere' },
  { label: 'Jura', value: 'jura' },
  { label: 'Landes', value: 'landes' },
  { label: 'Loir-et-Cher', value: 'loir-et-cher' },
  { label: 'Loire', value: 'loire' },
  { label: 'Haute-Loire', value: 'haute-loire' },
  { label: 'Loire-Atlantique', value: 'loire-atlantique' },
  { label: 'Loiret', value: 'loiret' },
  { label: 'Lot', value: 'lot' },
  { label: 'Lot-et-Garonne', value: 'lot-et-garonne' },
  { label: 'Lozère', value: 'lozere' },
  { label: 'Maine-et-Loire', value: 'maine-et-loire' },
  { label: 'Manche', value: 'manche' },
  { label: 'Marne', value: 'marne' },
  { label: 'Haute-Marne', value: 'haute-marne' },
  { label: 'Mayenne', value: 'mayenne' },
  { label: 'Meurthe-et-Moselle', value: 'meurthe-et-moselle' },
  { label: 'Meuse', value: 'meuse' },
  { label: 'Morbihan', value: 'morbihan' },
  { label: 'Moselle', value: 'moselle' },
  { label: 'Nièvre', value: 'nievre' },
  { label: 'Nord', value: 'nord' },
  { label: 'Oise', value: 'oise' },
  { label: 'Orne', value: 'orne' },
  { label: 'Pas-de-Calais', value: 'pas-de-calais' },
  { label: 'Puy-de-Dôme', value: 'puy-de-dome' },
  { label: 'Pyrénées-Atlantiques', value: 'pyrenees-atlantiques' },
  { label: 'Hautes-Pyrénées', value: 'hautes-pyrenees' },
  { label: 'Pyrénées-Orientales', value: 'pyrenees-orientales' },
  { label: 'Bas-Rhin', value: 'bas-rhin' },
  { label: 'Haut-Rhin', value: 'haut-rhin' },
  { label: 'Rhône', value: 'rhone' },
  { label: 'Haute-Saône', value: 'haute-saone' },
  { label: 'Saône-et-Loire', value: 'saone-et-loire' },
  { label: 'Sarthe', value: 'sarthe' },
  { label: 'Savoie', value: 'savoie' },
  { label: 'Haute-Savoie', value: 'haute-savoie' },
  { label: 'Paris', value: 'paris' },
  { label: 'Seine-Maritime', value: 'seine-maritime' },
  { label: 'Seine-et-Marne', value: 'seine-et-marne' },
  { label: 'Yvelines', value: 'yvelines' },
  { label: 'Deux-Sèvres', value: 'deux-sevres' },
  { label: 'Somme', value: 'somme' },
  { label: 'Tarn', value: 'tarn' },
  { label: 'Tarn-et-Garonne', value: 'tarn-et-garonne' },
  { label: 'Var', value: 'var' },
  { label: 'Vaucluse', value: 'vaucluse' },
  { label: 'Vendée', value: 'vendee' },
  { label: 'Vienne', value: 'vienne' },
  { label: 'Haute-Vienne', value: 'haute-vienne' },
  { label: 'Vosges', value: 'vosges' },
  { label: 'Yonne', value: 'yonne' },
  { label: 'Territoire de Belfort', value: 'territoire de belfort' },
  { label: 'Essonne', value: 'essonne' },
  { label: 'Hauts-de-Seine', value: 'hauts-de-seine' },
  { label: 'Seine-Saint-Denis', value: 'seine-saint-denis' },
  { label: 'Val-de-Marne', value: 'val-de-marne' },
  { label: "Val-d'Oise", value: 'val-doise' }
]

export const suportCountries = [
  { label: 'Spain', value: 'spain' },
  { label: 'France', value: 'france' }
]

export const propertyTypes = [
  'ruralproperty',
  'groundfloor',
  'townhouse',
  'apartment',
  'penthouse',
  'chalet',
  'duplex',
  'studio',
  'loft'
]
